# Generated by Django 2.1.1 on 2018-10-29 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camsapp', '0004_auto_20181027_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='member',
            field=models.CharField(default='', max_length=264),
            preserve_default=False,
        ),
    ]
